apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob3
  namespace: default
  labels:
   pod: notcronjob
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command: ["date"]
          restartPolicy: OnFailure
