apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: default
  annotations:
    offsetMinutes: "5"
spec:
  schedule: "{{ .Values.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command: ["date"]
            env:
            - name: CRON_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: cronjob-config
                  key: cronSchedule  
          restartPolicy: OnFailure