apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: default
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command: ["date"]
          restartPolicy: OnFailure
