apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: default
  annotations:
    offsetMinutes: "5" 
spec:
  schedule: "*/5 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: busybox
            command: ["date"]
          restartPolicy: OnFailure
